# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export LC_ALL="en_US.UTF-8"

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

for f in "${HOME}/.config/bash/"*; do
    . $f
done



# added by travis gem
[ ! -s /home/john/.travis/travis.sh ] || source /home/john/.travis/travis.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
