#!/bin/bash
herbstclient set_attr settings.frame_bg_transparent true 
herbstclient set_attr monitors.0.pad_up 17
herbstclient set_attr settings.focus_crosses_monitor_boundaries true
herbstclient rename default F1
herbstclient add F2
herbstclient add F3
herbstclient add F4
herbstclient set_attr settings.frame_border_active_color \#282828
herbstclient set_attr settings.bg_border_active_color \#bdae93
herbstclient set_attr settings.frame_border_normal_color \#282828
herbstclient set_attr settings.bg_border_normal_color \#fbf1c7
herbstclient set_attr settings.window_gap 3
herbstclient set_attr settings.frame_normal_opacity 0
herbstclient detect_monitors
