actions:
  setup: bash ~/scr/dotsetup
dynvariables:
  user: echo $USER
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
    chmod: '755'
  d_bash:
    src: config/bash
    dst: ~/.config/bash
  f_sxhkdrc:
    src: config/sxhkd/sxhkdrc
    dst: ~/.config/sxhkd/sxhkdrc
  d_mondo_gen:
    src: config/mondo/generator
    dst: ~/.config/mondo/generator
    upignore:
    - '*/*'
    - '!_*'
  d_mondo_thm:
    src: config/mondo/themes
    dst: ~/.config/mondo/themes
  d_scr:
    src: scr
    dst: ~/scr
  f_user-dirs.dirs:
    src: config/user-dirs.dirs
    dst: ~/.config/user-dirs.dirs
    chmod: '600'
  d_colors:
    src: config/nvim/colors
    dst: ~/.config/nvim/colors
  d_vscode-wal:
    src: vscode-oss/extensions/vscode-wal
    dst: ~/.vscode-oss/extensions/vscode-wal
    upignore:
    - '*'
  f_config.py:
    src: config/qutebrowser/config.py
    dst: ~/.config/qutebrowser/config.py
    chmod: '755'
  f_autoconfig.yml:
    src: config/qutebrowser/autoconfig.yml
    dst: ~/.config/qutebrowser/autoconfig.yml
  f_commands.py:
    src: config/ranger/commands.py
    dst: ~/.config/ranger/commands.py
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_rifle.conf:
    src: config/ranger/rifle.conf
    dst: ~/.config/ranger/rifle.conf
  f_scope.sh:
    src: config/ranger/scope.sh
    dst: ~/.config/ranger/scope.sh
    chmod: '755'
  f_monochrome.py:
    src: config/ranger/colorschemes/monochrome.py
    dst: ~/.config/ranger/colorschemes/monochrome.py
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '755'
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    chmod: '755'
  f_profile:
    src: profile
    dst: ~/.profile
  f_settings:
    src: config/linklord/settings
    dst: ~/.config/linklord/settings
  f_actions:
    src: config/linklord/actions
    dst: ~/.config/linklord/actions
    chmod: '600'
  f_dunst-settings:
    src: config/dunst/dunst-settings
    dst: ~/.config/dunst/dunst-settings
  f_dcatting.py:
    src: config/ranger/colorschemes/dcatting.py
    dst: ~/.config/ranger/colorschemes/dcatting.py
  f_settings.json:
    src: config/Code - OSS/User/settings.json
    dst: ~/.config/Code - OSS/User/settings.json
  f_keybindings.json:
    src: config/Code - OSS/User/keybindings.json
    dst: ~/.config/Code - OSS/User/keybindings.json
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  d_doom.d:
    src: doom.d
    dst: ~/.doom.d
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: '700'
  f_hyprland.conf:
    src: config/hypr/hyprland.conf
    dst: ~/.config/hypr/hyprland.conf
  f_hyprpaper.conf:
    src: config/hypr/hyprpaper.conf
    dst: ~/.config/hypr/hyprpaper.conf
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
  d_user:
    src: config/nvim/lua/user
    dst: ~/.config/nvim/lua/user
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
    chmod: '777'
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_budland.conf:
    src: config/budland/budland.conf
    dst: ~/.config/budland/budland.conf
  f_pre-apply:
    src: config/mondo/pre-apply
    dst: ~/.config/mondo/pre-apply
  f_post-apply:
    src: config/mondo/post-apply
    dst: ~/.config/mondo/post-apply
    chmod: '755'
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  d_prestosilver:
    src: config/nvim/lua/prestosilver
    dst: ~/.config/nvim/lua/prestosilver
profiles:
  john-pc:
    actions:
    - setup
    dotfiles:
    - f_xinitrc
    - d_bash
    - f_sxhkdrc
    - d_mondo_gen
    - d_mondo_thm
    - d_scr
    - f_user-dirs.dirs
    - d_colors
    - d_vscode-wal
    - f_config.py
    - f_autoconfig.yml
    - f_commands.py
    - f_rc.conf
    - f_rifle.conf
    - f_scope.sh
    - f_monochrome.py
    - f_bashrc
    - f_xresources
    - f_profile
    - f_settings
    - f_actions
    - f_dunst-settings
    - f_dcatting.py
    - f_settings.json
    - f_picom.conf
    - f_keybindings.json
    - d_doom.d
    - d_fish
    - f_hyprland.conf
    - f_hyprpaper.conf
    - f_init.lua
    - d_user
    - d_waybar
    - d_kitty
    - f_budland.conf
    - f_pre-apply
    - f_post-apply
    - f_alacritty.yml
    - d_prestosilver
