#!/bin/bash
tmp="$(playerctl metadata | grep xesam)"

[ -x "$tmp" ] && exit

artist=$(echo "$tmp" | grep "artist " | sed "s/.*:artist //" | sed "s/^ *//")
album=$(echo "$tmp" | grep "album " | sed "s/.*:album //" | sed "s/^ *//")
track=$(echo "$tmp" | grep "title " | sed "s/.*:title //" | sed "s/^ *//")

cache="$artist - $album"

[ "$cache" == "$(cat /tmp/cover.txt)" ] && exit

sacad "$artist" "$album" 160 "/tmp/cover.jpeg" -v quiet
printf "%s" "$cache" > /tmp/cover.txt
kill -RTMIN+15 $(pidof waybar)
notify-send -u low -i "/tmp/cover.jpeg" "$track" "$artist" 
