#!/bin/bash
[[ $(ip -o link | grep 'state UP' | grep -v LOOPBACK | grep -v '^lo' | grep -v '^brd' | grep -v '^scope-id' | grep -v '^type' | grep -v '^inet' | grep -v '^inet6' | grep -v '^brd' | grep -v '^scope-id' | grep -v '^type' | grep -v '^inet' | grep -v '^inet6') == "" ]] && exit

tmp="$(playerctl metadata | grep xesam)"

[ -x "$tmp" ] && exit

artist=$(echo "$tmp" | grep "artist " | sed "s/.*:artist //" | sed "s/^ *//")
album=$(echo "$tmp" | grep "album " | sed "s/.*:album //" | sed "s/^ *//")
track=$(echo "$tmp" | grep "title " | sed "s/.*:title //" | sed "s/^ *//")

cache="$artist - $album"

[ "$cache" != "$(cat /tmp/cover.txt)" ] || exit

sacad "$artist" "$album" 50 "/tmp/cover.jpeg" -v quiet
echo $cache > /tmp/cover.txt
kill -RTMIN+15 $(pidof waybar)
notify-send -i "/tmp/cover.jpeg" "$track" "$artist" 
