#!/bin/bash
bemenu-run --fn "CaskaydiaCovePL Nerd Font" -H 20 \
    --hp 10 -c --list 15 -W 0.5 \
    --ab '#BD9B61' \
    --af '#9F7A39' \
    --nb '#BD9B61' \
    --nf '#9F7A39' \
    --hb '#FF8C57' \
    --hf '#ffffff' \
    --fb '#BD9B61' \
    --ff '#9F7A39' \
    --fbb '#FF8C57' \
    --fbf '#ffffff' \
    --tb '#FF8C57' \
    --tf '#ffffff' \
    --bdr '#F77438' \
    -B 2 --fixed-height --scrollbar --counter
