#!/bin/bash
#killall -KILL swaybg
#[[ "" == "$(mondo -c wall)" ]] || swaybg --color $(mondo -c wall) && swaybg --color=$(mondo -c bg) &
# swaybg --image=$HOME/pix/wallpapers/currentwall --mode=fill &

color=$(mondo -c wall)
convert -size 100x100 "xc:$color" ~/pix/wall.png
swww img ~/pix/wall.png --transition-type outer -f Nearest --transition-fps 60
