#!/bin/bash
#killall -KILL swaybg
#[[ "" == "$(mondo -c wall)" ]] || swaybg --color $(mondo -c wall) && swaybg --color=$(mondo -c bg) &
# swaybg --image=$HOME/pix/wallpapers/currentwall --mode=fill &
#
set -xe

#color=$(mondo -c wall)
#convert -size 100x100 "xc:$color" ~/pix/wallpapers/wall.png
#feh --bg-fill ~/pix/wallpapers/wall.png
feh --bg-fill ~/pix/wallpapers/wall.jpg
#swww img ~/pix/wallpapers/wall.png

#swww img ~/pix/wallpapers/wall.jpg --transition-type outer -f Nearest --transition-fps 60
